name: Run Unit Tests

permissions:
  contents: read

on:
  push:
    branches: [ "main", "develop", "tests" ]
  pull_request:
    branches: [ "main", "develop", "tests" ]

jobs:
  test:
    name: Run tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          clean: true
          persist-credentials: false
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: REDKARASIK/geometric_lib
          sparse-checkout-cone-mode: true
          fetch-tags: false
          show-progress: true
          lfs: false
          set-safe-directory: true
          ssh-strict: true
          ssh-user: git
          submodules: false

      - name: Clear GitHub Actions Cache (if any)
        run: |
          rm -rf ~/.cache

      - name: Remove old Git configuration (if any)
        run: |
          git config --global --unset-all core.sshCommand
          git config --global --unset-all http.https://github.com/.extraheader
          git gc --prune=now

      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Unit tests
        run: |
          python -m unittest discover -s test

    timeout-minutes: 30
