name: Run Unit Tests

permissions:
  contents: read

on:
  push:
    branches: [ "main", "develop", "tests" ]
  pull_request:
    branches: [ "main", "develop", "tests" ]

jobs:
  test:
    name: Run tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: List test directory
        run: ls test

      - name: Fix Windows Paths
        if: runner.os == 'Windows'
        run: |
          python -m pip install --upgrade pip
          pip install setuptools

      - name: Unit tests
        run: |
          python -m unittest discover -s test
