name: Run Unit Tests

on:
  push:
    branches: [ "main", "develop", "tests" ]
  pull_request:
    branches: [ "main", "develop", "tests" ]


jobs:
  test:
    name: Run tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Unit tests
        run: |
          python -m unittest discover -s test
      
